### ISSUE TITLE
Consumed objects in apis/wsecurity/v1alpha1

### ISSUE THREAD

**Issue by davidhadas** [knative-sandbox/security-guard#30]
At the apis/wsecurity/v1alpha1 package:
 
Once an object is consumed, it should no longer be used. 
The code should change to protect against silent data corruption as package users may try to use consumed objects 

Options: 
  * Clear consumed objects always
  * Clear consumed objects only if actually consumed and should no longer be ued

Need to be evaluated once all data Types are there and fixed.

**Comment by maximilien** [comment]
By clear do you mean objects should be "garbage collected"? If yes then just ensure no reference to the object exist...

**Comment by davidhadas** [comment]
In this context, when indicating an object is consumed, the meaning is that it is "used" as part of the collection. 
For example, 
* When we have a pile.Add(profile) then the profile is consumed by pile (and should no longer be used elsewhere)
* When we have a config.Learn(pile) then the pile is consumed by config (and should no longer be used elsewhere)

**Comment by davidhadas** [comment]
implemented in https://github.com/knative-sandbox/security-guard/pull/90 
/close
