### ISSUE TITLE
Authenticate requests from guard-service 

### ISSUE THREAD

**Issue by davidhadas** [knative-sandbox/security-guard#71]
Currently, none of the requests to guard-service are authenticated. 
We, therefore, trust that anyone with access to guard-service is in the same trust domain and can read all guardians. 
But the concern is greater since guard-service  writes to the learned section of the guardian and hence anyone in the trust domain can pretend to be someone else effectively changing the learned section - supporting a lateral movement of an offender in the trust domain. 

Authenticating all requests to guard-service is needed. 
Caching of authenticated tokens is also needed to minimize the affect on KubeAPI

**Comment by davidhadas** [comment]
The suggested implementation follows: https://learnk8s.io/microservices-authentication-kubernetes
@evankanderson  - discuss current queue token support vs. what we need

**Comment by evankanderson** [comment]
Yes, using projected tokens **with a unique `aud`ience** is a reasonable and safe approach for this.

Another reasonable and mostly-safe approach is to have the guardian dial **TO** the queue proxies, and enforce the pod's identity on the collected data.

**Comment by davidhadas** [comment]
Lets go with  projected tokens with a unique audience

The other option requires that the QP is timely approached when it needs the Guardian content (when QP is otherwise ready to serve and before the request is processed) or when it has a pile to report and is about to shutdown.
